// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flhuvtpxisdfpqeahiov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaHV2dHB4aXNkZnBxZWFoaW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTkwMzEsImV4cCI6MjA3MzIzNTAzMX0.iTMRMame-6U0NdwcL2K8-E-oJ3LKAhNY_pMZER6IYeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});